### ISSUE TITLE
Calendar picker does not show icons properly

### ISSUE THREAD

**Issue by petrjahoda** [olton/metroui#1981]
**Describe the bug**
Calendar picker is not showing icons for left and right in month and year.

**To Reproduce**
No need to reproduce, it is visible in pandora https://panda.metroui.org.ua/ui/calendar

**Expected behavior**
Show icons.

**Screenshots**
<img width="923" alt="Image" src="https://github.com/user-attachments/assets/ebb9afa1-9226-4753-a9e4-52a81fe31b90" />

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Metro Version 5.1.2

**Smartphone (please complete the following information):**
- None

**Additional context**

**Comment by olton** [comment]
![Image](https://github.com/user-attachments/assets/a4e76540-1615-4761-802d-38837fbb9711)

**Comment by petrjahoda** [comment]
OK, looks like the problem is with macOS, even Chrome shows it without those "left" and "right" arrows.

**Comment by olton** [comment]
as a temporary solution, you can set the icons yourself with attributes: `data-prev-month-icon`, `data-next-month-icon`, `data-prev-year-icon`, `data-next-year-icon`

```html
<div data-role="calendar" data-prev-month-icon="..." ...>
</div>
```

**Comment by petrjahoda** [comment]
Going to do it, iOS the same.

**Comment by olton** [comment]
Also you can change default fornt for these buttons:
```css
.calendar-content {
    .calendar-toolbar {
        .prev-month, .prev-year, .next-month, .next-year, .next-year-group, .prev-year-group {
            forn-family: '...';
        }
    }
}
```
